// <auto-generated />
using System;
using Genlogs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genlogs.Api.Data.Migrations
{
    [DbContext(typeof(GenlogsDbContext))]
    [Migration("20260904153454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Genlogs.Api.Models.Carrier", b =>
                {
                    b.Property<int>("CarrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsdotNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CarrierId");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("Genlogs.Api.Models.DetectionEvent", b =>
                {
                    b.Property<int>("DetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LaneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetectionId");

                    b.HasIndex("LaneId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DetectionEvents");
                });

            modelBuilder.Entity("Genlogs.Api.Models.Lane", b =>
                {
                    b.Property<int>("LaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefaultFallback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LaneId");

                    b.HasIndex("OriginCity", "DestinationCity")
                        .IsUnique();

                    b.ToTable("Lanes");
                });

            modelBuilder.Entity("Genlogs.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarrierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId");

                    b.HasIndex("CarrierId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Genlogs.Api.Models.DetectionEvent", b =>
                {
                    b.HasOne("Genlogs.Api.Models.Lane", "Lane")
                        .WithMany("DetectionEvents")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genlogs.Api.Models.Vehicle", "Vehicle")
                        .WithMany("DetectionEvents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lane");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Genlogs.Api.Models.Vehicle", b =>
                {
                    b.HasOne("Genlogs.Api.Models.Carrier", "Carrier")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("Genlogs.Api.Models.Carrier", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Genlogs.Api.Models.Lane", b =>
                {
                    b.Navigation("DetectionEvents");
                });

            modelBuilder.Entity("Genlogs.Api.Models.Vehicle", b =>
                {
                    b.Navigation("DetectionEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
